
name: Artifact Upload and Download Example

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: echo "Data file" > data.txt- name: Upload file as 
        uses: actions/upload-artifact@v4
        with:
          name: datafile
          path: data.txt
        
